FROM ghcr.io/astral-sh/uv:0.9.2-python3.13-bookworm-slim

WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN UV_HTTP_TIMEOUT=120 uv sync --frozen --no-install-project

COPY . .
RUN uv sync --frozen

EXPOSE 8000
CMD ["uv", "run", "fastapi", "dev", "main.py", "--host", "0.0.0.0", "--port", "8000"]
